services:
  - type: web
    name: ecomine
    env: node
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: MAPTILER_API_KEY
        sync: false
    plan: free 